import os

env = Environment(ENV = os.environ, tools = ["default", compile_matlab_code])

matlab_examples = []

for name in ["1_0", "1_1", "1_2", "1_3"]:
    filename = "example{0:s}".format(name)
    env.MATLAB(filename)
    matlab_examples.append(filename + ".m")

env.Depends("lecture1.pdf", matlab_examples)
env.PDF("lecture1.tex")
